# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine AS builder
WORKDIR /app
# Install dependencies without running prepare scripts
COPY package.json package-lock.json tsconfig.json build.ts ./
COPY src ./src
RUN npm ci --ignore-scripts
RUN npm run build

FROM node:lts-alpine AS runtime
WORKDIR /app
# Copy built artifacts and dependencies
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
# Copy resource files
COPY agent-keys.txt ./agent-keys.txt
COPY USAGE.md ./USAGE.md
COPY STELLAR_TOKENS_SAC.md ./STELLAR_TOKENS_SAC.md

# Default command
CMD ["node", "build/mcp-server.js"]
